# Generated by Django 6.0.5 on 2026-09-09 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front_side', models.CharField(max_length=150)),
                ('back_side', models.CharField(max_length=150)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to='flashcard_api.deck')),
            ],
        ),
        migrations.CreateModel(
            name='FcReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewed_at', models.DateTimeField()),
                ('rating', models.CharField(choices=[(0, 'Again'), (1, 'Hard'), (2, 'Good'), (3, 'Easy')])),
                ('flashcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='flashcard_api.flashcard')),
            ],
        ),
        migrations.CreateModel(
            name='FcProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_at', models.DateField()),
                ('last_reviewed_at', models.DateTimeField()),
                ('repetitions', models.PositiveIntegerField(default=0)),
                ('ease_factor', models.FloatField(default=2.5)),
                ('interval', models.PositiveIntegerField(default=0)),
                ('flashcard', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='flashcard_api.flashcard')),
            ],
        ),
    ]
