# Generated by Django 6.0.5 on 2026-09-19 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='description',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
