# Generated by Django 6.1.1 on 2026-09-21 23:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard_api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='deck',
            index=models.Index(fields=['is_public'], name='flashcard_a_is_publ_5b44cc_idx'),
        ),
    ]
