# Generated by Django 6.0.5 on 2026-09-11 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fcreview',
            name='flashcard',
        ),
        migrations.AlterField(
            model_name='deck',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_at', models.DateTimeField()),
                ('last_reviewed_at', models.DateTimeField(null=True)),
                ('successful_repetitions', models.PositiveIntegerField(default=0)),
                ('ease_factor', models.FloatField(default=2.5)),
                ('interval', models.PositiveIntegerField(default=0)),
                ('flashcard', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='flashcard_api.flashcard')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('rating', models.IntegerField(choices=[(2, 'Again'), (3, 'Hard'), (4, 'Good'), (5, 'Easy')])),
                ('flashcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='flashcard_api.flashcard')),
            ],
        ),
        migrations.DeleteModel(
            name='FcProgress',
        ),
        migrations.DeleteModel(
            name='FcReview',
        ),
    ]
