# Generated by Django 6.0.5 on 2026-09-11 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard_api', '0002_remove_fcreview_flashcard_alter_deck_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='due_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
